USE [master]
GO

/****** Object:  Database [Pharma]    Script Date: 7/5/2023 12:21:09 AM ******/
CREATE DATABASE [Pharma]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'C:\USERS\CAFE MANGMENT SYSTEM\phar', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\C__USERS_CAFE MANGMENT SYSTEM_phar.mdf' , SIZE = 3264KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'C__USERS_CAFE MANGMENT SYSTEM_phar_log', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\C__USERS_CAFE MANGMENT SYSTEM_phar_log.ldf' , SIZE = 816KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Pharma] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Pharma].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Pharma] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Pharma] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Pharma] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Pharma] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Pharma] SET ARITHABORT OFF 
GO

ALTER DATABASE [Pharma] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Pharma] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Pharma] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Pharma] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Pharma] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Pharma] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Pharma] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Pharma] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Pharma] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Pharma] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Pharma] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Pharma] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Pharma] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Pharma] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Pharma] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Pharma] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Pharma] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Pharma] SET RECOVERY FULL 
GO

ALTER DATABASE [Pharma] SET  MULTI_USER 
GO

ALTER DATABASE [Pharma] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Pharma] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Pharma] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Pharma] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Pharma] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Pharma] SET  READ_WRITE 
GO

